import type { Product } from '../types/product';

export const products: Product[] = [
  {
    id: 'nike-air-zoom-pegasus',
    brand: 'Nike',
    name: 'Air Zoom Pegasus 40',
    category: 'Running',
    price: 129.99,
    rating: 4.8,
    colors: ['Black', 'White', 'Orange'],
    image: 'https://images.unsplash.com/photo-1519741494122-5f5d8a5dc71c?auto=format&fit=crop&w=900&q=80',
    description: 'Giày chạy bộ đa năng với đệm Zoom Air êm ái và thiết kế hiện đại.',
    features: ['Cushioning Zoom Air', 'Mesh upper', 'Rubber outsole'],
  },
  {
    id: 'nike-air-max-270',
    brand: 'Nike',
    name: 'Air Max 270',
    category: 'Lifestyle',
    price: 149.99,
    rating: 4.7,
    colors: ['White', 'Black', 'Orange'],
    image: 'https://images.unsplash.com/photo-1528701800489-20b73bbf80e2?auto=format&fit=crop&w=900&q=80',
    description: 'Phong cách đường phố với bọt êm và khối Air lớn ở gót.',
    features: ['Air unit heel', 'Synthetic leather', 'Supportive fit'],
  },
  {
    id: 'adidas-ultraboost-light',
    brand: 'Adidas',
    name: 'Ultraboost Light',
    category: 'Running',
    price: 159.99,
    rating: 4.9,
    colors: ['Black', 'White', 'Grey'],
    image: 'https://images.unsplash.com/photo-1552346154-ef8f39a0cee9?auto=format&fit=crop&w=900&q=80',
    description: 'Thân thiện với đôi chân, phù hợp chạy đường dài và sử dụng hàng ngày.',
    features: ['Boost midsole', 'Primeknit upper', 'Continental outsole'],
  },
  {
    id: 'adidas-superstar',
    brand: 'Adidas',
    name: 'Superstar',
    category: 'Casual',
    price: 99.99,
    rating: 4.6,
    colors: ['White', 'Black'],
    image: 'https://images.unsplash.com/photo-1519741494125-1efd8e1fc39f?auto=format&fit=crop&w=900&q=80',
    description: 'Giày cổ điển mang đậm phong cách streetwear với mũi giày vỏ sò đặc trưng.',
    features: ['Leather upper', 'Rubber shell toe', 'Classic design'],
  },
  {
    id: 'puma-rider',
    brand: 'Puma',
    name: 'Puma Rider Future',
    category: 'Training',
    price: 119.99,
    rating: 4.5,
    colors: ['Black', 'Orange'],
    image: 'https://images.unsplash.com/photo-1618354695830-95207a9a8905?auto=format&fit=crop&w=900&q=80',
    description: 'Giày tập luyện với đệm êm và thiết kế thời thượng.',
    features: ['Soft foam', 'Textile upper', 'Durable traction'],
  },
  {
    id: 'puma-cali-star',
    brand: 'Puma',
    name: 'Cali Star',
    category: 'Lifestyle',
    price: 104.99,
    rating: 4.4,
    colors: ['White', 'Peach'],
    image: 'https://images.unsplash.com/photo-1555435023-1dd1f6d5f4f4?auto=format&fit=crop&w=900&q=80',
    description: 'Thiết kế phong cách đường phố với phần đế cao và dáng thời thượng.',
    features: ['Platform sole', 'Leather upper', 'Retro aesthetic'],
  },
  {
    id: 'converse-chuck-taylor',
    brand: 'Converse',
    name: 'Chuck Taylor All Star',
    category: 'Casual',
    price: 64.99,
    rating: 4.3,
    colors: ['White', 'Black'],
    image: 'https://images.unsplash.com/photo-1519741494120-33f455ae98d3?auto=format&fit=crop&w=900&q=80',
    description: 'Giày cổ cao kinh điển, dễ phối đồ và phù hợp phong cách streetwear.',
    features: ['Canvas upper', 'Rubber sole', 'Iconic silhouette'],
  },
  {
    id: 'converse-run-star-hike',
    brand: 'Converse',
    name: 'Run Star Hike',
    category: 'Lifestyle',
    price: 89.99,
    rating: 4.5,
    colors: ['Black', 'White'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    description: 'Giày cao cổ với đế răng cưa cá tính, phù hợp phong cách streetwear hiện đại.',
    features: ['Platform sole', 'Canvas upper', 'Trail outsole'],
  },
  {
    id: 'newbalance-550',
    brand: 'New Balance',
    name: '550',
    category: 'Casual',
    price: 109.99,
    rating: 4.6,
    colors: ['White', 'Navy'],
    image: 'https://images.unsplash.com/photo-1474875135348-04e0de7003b8?auto=format&fit=crop&w=900&q=80',
    description: 'Giày cổ điển với cảm hứng từ phong cách retro thập niên 80.',
    features: ['Leather upper', 'Rubber outsole', 'Vintage design'],
  },
  {
    id: 'newbalance-827',
    brand: 'New Balance',
    name: '827',
    category: 'Running',
    price: 129.99,
    rating: 4.7,
    colors: ['Grey', 'Orange'],
    image: 'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=900&q=80',
    description: 'Phiên bản running cổ điển cho phong cách khỏe khoắn và năng động.',
    features: ['ABZORB cushioning', 'Suede upper', 'Durable traction'],
  },
  {
    id: 'nike-dunk-low',
    brand: 'Nike',
    name: 'Dunk Low',
    category: 'Lifestyle',
    price: 119.99,
    rating: 4.8,
    colors: ['White', 'Orange', 'Black'],
    image: 'https://images.unsplash.com/photo-1508264165352-258a7d4687c0?auto=format&fit=crop&w=900&q=80',
    description: 'Giày bóng rổ classic phong cách streetwear, dễ phối đồ.',
    features: ['Leather upper', 'Foam midsole', 'Padded collar'],
  },
  {
    id: 'adidas-nmd-r1',
    brand: 'Adidas',
    name: 'NMD R1',
    category: 'Lifestyle',
    price: 139.99,
    rating: 4.6,
    colors: ['Black', 'Grey'],
    image: 'https://images.unsplash.com/photo-1600185367432-9db9152a3e1a?auto=format&fit=crop&w=900&q=80',
    description: 'Giày thành thị trẻ trung với đệm Boost mềm mại và thẩm mỹ hiện đại.',
    features: ['Boost midsole', 'Sock-like upper', 'EVA plugs'],
  },
  {
    id: 'puma-clyde',
    brand: 'Puma',
    name: 'Clyde',
    category: 'Casual',
    price: 89.99,
    rating: 4.4,
    colors: ['White', 'Black'],
    image: 'https://images.unsplash.com/photo-1528701800489-39eb76bc7c70?auto=format&fit=crop&w=900&q=80',
    description: 'Giày streetwear thời thượng với thiết kế tối giản và bền bỉ.',
    features: ['Leather upper', 'Rubber outsole', 'Low profile'],
  },
  {
    id: 'newbalance-1080',
    brand: 'New Balance',
    name: '1080v12',
    category: 'Running',
    price: 159.99,
    rating: 4.9,
    colors: ['Black', 'Orange'],
    image: 'https://images.unsplash.com/photo-1580910051072-11d09a28482f?auto=format&fit=crop&w=900&q=80',
    description: 'Giày chạy bộ cao cấp với đệm Fresh Foam cực êm và hỗ trợ tối ưu.',
    features: ['Fresh Foam', 'Hypoknit upper', 'Blown rubber outsole'],
  },
  {
    id: 'nike-blazer-mid',
    brand: 'Nike',
    name: 'Blazer Mid',
    category: 'Lifestyle',
    price: 109.99,
    rating: 4.7,
    colors: ['White', 'Orange'],
    image: 'https://images.unsplash.com/photo-1528701800489-d8204b6a4988?auto=format&fit=crop&w=900&q=80',
    description: 'Giày cổ cao kinh điển dành cho phong cách streetwear năng động.',
    features: ['Leather upper', 'Rubber cupsole', 'High-top silhouette'],
  },
  {
    id: 'adidas-forum-low',
    brand: 'Adidas',
    name: 'Forum Low',
    category: 'Lifestyle',
    price: 119.99,
    rating: 4.5,
    colors: ['White', 'Orange'],
    image: 'https://images.unsplash.com/photo-1618354695830-34567f6a8905?auto=format&fit=crop&w=900&q=80',
    description: 'Giày bóng rổ retro phong cách đường phố, dễ phối quần áo.',
    features: ['Leather upper', 'Two-strap closure', 'Cushioned midsole'],
  },
  {
    id: 'puma-accelerate',
    brand: 'Puma',
    name: 'Accelerate Nitro',
    category: 'Running',
    price: 149.99,
    rating: 4.8,
    colors: ['Black', 'White', 'Orange'],
    image: 'https://images.unsplash.com/photo-1580910051072-41d09a28482f?auto=format&fit=crop&w=900&q=80',
    description: 'Giày chạy bộ hiệu suất cao với đệm Nitro siêu nhẹ.',
    features: ['Nitro foam', 'Engineered mesh', 'Rubber outsole'],
  },
  {
    id: 'converse-chuck-70',
    brand: 'Converse',
    name: 'Chuck 70',
    category: 'Casual',
    price: 74.99,
    rating: 4.5,
    colors: ['Black', 'White'],
    image: 'https://images.unsplash.com/photo-1519741494123-6f5a8f1ac39f?auto=format&fit=crop&w=900&q=80',
    description: 'Phiên bản Chuck Taylor nâng cấp với chất liệu bền và đế êm hơn.',
    features: ['Canvas upper', 'Enhanced cushioning', 'Retro detail'],
  },
  {
    id: 'adidas-gazelle',
    brand: 'Adidas',
    name: 'Gazelle',
    category: 'Casual',
    price: 99.99,
    rating: 4.6,
    colors: ['Navy', 'White'],
    image: 'https://images.unsplash.com/photo-1528701800489-7037b5aa5f70?auto=format&fit=crop&w=900&q=80',
    description: 'Giày cổ điển dễ phối đồ, phù hợp phong cách casual hiện đại.',
    features: ['Suede upper', 'Rubber outsole', 'Classic stripes'],
  },
  {
    id: 'nike-react-infinity',
    brand: 'Nike',
    name: 'React Infinity Run',
    category: 'Running',
    price: 169.99,
    rating: 4.8,
    colors: ['Black', 'Orange'],
    image: 'https://images.unsplash.com/photo-1519741494121-0c5d8a4bc71c?auto=format&fit=crop&w=900&q=80',
    description: 'Giày chạy bộ hỗ trợ giảm chấn với đệm React linh hoạt.',
    features: ['React foam', 'Flyknit upper', 'Wide base'],
  },
  {
    id: 'newbalance-574',
    brand: 'New Balance',
    name: '574 Core',
    category: 'Casual',
    price: 89.99,
    rating: 4.4,
    colors: ['Grey', 'White'],
    image: 'https://images.unsplash.com/photo-1508264165352-22222d4687c0?auto=format&fit=crop&w=900&q=80',
    description: 'Một trong những đôi giày dễ đi nhất với thiết kế retro hiện đại.',
    features: ['Suede/mesh upper', 'ENCAP midsole', 'Classic profile'],
  }
];
